- name: Development environment playbook
  hosts: localhost
  tasks:
    - name: Install packages using apt
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - zsh
          - docker
          - cmake
        state: present # could also be 'latest' or 'absent'
    # - name: Install oh-my-zsh
    #   become: yes
    # - name: Install emacs
    #   become: yes

- name: i3 wm playbook
  hosts: localhost
  tasks:
    i3
    - name: Install i3
      become: yes
      tags:
        - i3
      ansible.builtin.apt:
        name:
          - i3
          - i3lock
          - i3status
          - compton
          - fonts-font-awesome
          - feh


    # polybar
    - name: Install polybar
      become: yes
      ansible.builtin.apt:
        name:
          - polybar
    - name: Setup spotify status for polybar
      become: yes
      ansible.builtin.copy:
        src: ./polybar/spotify_status.py
        dest: ~/.config/polybar/spotify_status.py
        mode: u=rwx, g=r, o=r # Make file executable ?


    # Rofi
    - name: Install rofi
      become: yes
      tags:
        - rofi
      ansible.builtin.apt:
        name:
          - rofi
        state: present

    - name: Copy rofi config file
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/config.rasi
        dest: ~/.config/rofi/config.rasi

    - name: Copy rofi slate theme file
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/slate_theme.rasi
        dest: ~/.config/rofi/slate_theme.rasi

    - name: Copy rofi monokai theme file
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/monokai_theme.rasi
        dest: ~/.config/rofi/monokai_theme.rasi

    - name: Copy gruvbox common
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/gruvbox-common.rasinc
        dest: ~/.config/rofi/gruvbox-common.rasi
      when: ansible_distribution == "Ubuntu"

    - name: Copy gruvbox dark hard theme
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/gruvbox-dark-hard_theme.rasi
        dest: ~/.config/rofi/gruvbox-dark-hard_theme.rasi
      when: ansible_distribution == "Ubuntu"
