---
- name: Install polybar in Debian
  when: ansible_facts['os_family']|lower == 'debian'
  ansible.builtin.import_tasks: debian.yaml

- name: Install polybar in Arch
  when: ansible_facts['os_family']|lower == 'arch'
  ansible.builtin.import_tasks: arch.yaml

- name: Create a directory for polybar if it does not exist
  ansible.builtin.file:
    path: ~/.config/polybar
    state: directory
    mode: "0600"

- name: Copy polybar config files
  ansible.builtin.copy:
    src: ../polybar/config
    dest: ~/.config/polybar/config
    mode: u=rwx,g=r,o=r

- name: Copy polybar launch script
  ansible.builtin.copy:
    src: ../polybar/launch.sh
    dest: ~/.config/polybar/launch.sh
    mode: u=rwx,g=r,o=r

- name: Setup spotify status for polybar
  ansible.builtin.copy:
    src: ../polybar/spotify_status.py
    dest: ~/.config/polybar/spotify_status.py
    mode: u=rwx,g=r,o=r
