---
# Cargo
- name: Check if cargo is installed
  ansible.builtin.command:
    argv:
      - command
      - -v
      - cargo
  register: cargo_exists
  ignore_errors: true

- name: Download Installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Install rust/cargo
  when: cargo_exists is failed
  ansible.builtin.command:
    argv:
      - /tmp/sh.rustup.rs
      - -y
  tags:
    - rust

# Homebrew
- name: Check if brew is installed
  ansible.builtin.command:
    argv:
      - command
      - -v
      - brew
  register: brew_exists
  ignore_errors: true

- name: Download homebrew installer
  when: brew_exists is failed
  ansible.builtin.get_url:
    # TODO Is the flags -fsSL needed?
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install.sh
    mode: '0755'
    force: 'yes'
  tags:
    - homebrew

- name: Install homebrew
  when: brew_exists is failed
  ansible.builtin.shell:
    argv:
      - /tmp/install.sh
      - -y # TODO is -y needed?
  tags:
    - homebrew
