---
- name: Install rofi in Debian
  when: ansible_facts['os_family']|lower == 'debian'
  ansible.builtin.import_tasks: debian.yaml

- name: Install rofi in Arch
  when: ansible_facts['os_family']|lower == 'arch'
  ansible.builtin.import_tasks: arch.yaml

- name: Create a directory for rofi if it does not exist
  ansible.builtin.file:
    path: ~/.config/rofi
    state: directory
    mode: "0755"

- name: Copy rofi config file
  tags:
    - rofi
  ansible.builtin.copy:
    src: ../rofi/config.rasi
    dest: ~/.config/rofi/config.rasi
    mode: "0600"

- name: Copy gruvbox common
  tags:
    - rofi
  ansible.builtin.copy:
    src: ../rofi/gruvbox-common.rasinc
    dest: ~/.config/rofi/gruvbox-common.rasi
    mode: "0600"

- name: Copy rofi gruvbox material theme
  tags:
    - rofi
  ansible.builtin.copy:
    src: ../rofi/gruvbox-material_theme.rasi
    dest: ~/.config/rofi/gruvbox-material_theme.rasi
    mode: "0600"
