---
- name: Apt update and upgrade
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"

- name: Install i3
  become: true
  ansible.builtin.apt:
    name: "{{ applications }}"
