---
- name: Install i3 in Debian
  when: ansible_facts['os_family']|lower == 'debian'
  ansible.builtin.import_tasks: debian.yaml

- name: Install i3 in Arch
  when: ansible_facts['os_family']|lower == 'arch'
  ansible.builtin.import_tasks: arch.yaml

- name: Copy i3 config files
  ansible.builtin.copy:
    src: ../i3/config
    dest: ~/.config/i3/config
    mode: u=rwx,g=r,o=r
