---

    # Emacs
    # - name: Install emacs dependencies
    #   become: yes
    #   ansible.builtin.apt:
    #     pkg: emacs
    #     state: build-dep

#    - name: Download emacs v29
#      ansible.builtin.get_url:
#        url: https://ftp.gnu.org/pub/gnu/emacs/emacs-29.1.tar.gz
#        dest: ~/emacs-29.1.tar.gz
#        become: yes

#    - name: Install spacemacs
#      become: yes

#    - name: Copy spacemacs dotfile
#      become: yes
#      ansible.buildin.copy:
#        src: ../spacemacs/.spacemacs
#        dest: ~/.spacemacs
