---
- name: Development environment playbook Ubuntu
  hosts: localhost
  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        # upgrade: "yes"

    - name: Install packages using apt
      become: true
      ansible.builtin.apt:
        name:
          - git
          - docker
          - cmake
          - build-essential
        state: present

    # Emacs
    # - name: Install emacs dependencies
    #   become: yes
    #   ansible.builtin.apt:
    #     pkg: emacs
    #     state: build-dep

#    - name: Download emacs v29
#      ansible.builtin.get_url:
#        url: https://ftp.gnu.org/pub/gnu/emacs/emacs-29.1.tar.gz
#        dest: ~/emacs-29.1.tar.gz
#        become: yes

#    - name: Install spacemacs
#      become: yes

#    - name: Copy spacemacs dotfile
#      become: yes
#      ansible.buildin.copy:
#        src: ../spacemacs/.spacemacs
#        dest: ~/.spacemacs

- name: Zsh and oh-my-zsh
  hosts: localhost
  tasks:
    - name: Install zsh
      become: true
      ansible.builtin.apt:
        name:
          - zsh
        state: present

    # TODO Maybe split this up so not shell is doing too much
    - name: Install oh-my-zsh
      become: true
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      register: output
      changed_when: output.rc != 0

    - name: Download oh-my-zsh theme
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        clone: true
        dest: ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
        depth: 1
        version: 0cc19ac

    - name: Copy oh-my-zsh dotfile
      ansible.builtin.copy:
        src: ../oh-my-zsh/.zshrc
        dest: ~/.zshrc
        mode: "0600"

    # - name: Restart zsh
    #   become: true
    #   ansible.builtin.command: source .zshrc
    #   register: output
    #   changed_when: output.rc != 0
