---
- name: Development environment playbook Ubuntu
  hosts: localhost
  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        # upgrade: "yes"

    - name: Install packages using apt
      become: true
      ansible.builtin.apt:
        name:
          - git
          - docker
          - cmake
          - build-essential
        state: present
  roles:
    - package_managers
    - zsh
    # - emacs
    - go

# - name: Development environment playbook arch
#   hosts: localhost
#   tasks:
#     - name: Install pacman packages
#       community.general.pacman:
#         name:
#           - unrar
#           - tar
#           - libreoffice
#           - git
#           - docker
#         state: present
