---
- name: Development environment playbook Ubuntu
  hosts: localhost
  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        # upgrade: "yes"

    - name: Install packages using apt
      become: true
      ansible.builtin.apt:
        name:
          - git
          - docker
          - cmake
          - build-essential
        state: present
  roles:
    - zsh
    # - emacs
    - go
