
- name: i3 wm playbook
  hosts: localhost
  tasks:
    - name: Apt update and upgrade
      become: yes
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

    # i3
    - name: Install i3
      become: yes
      tags:
        - i3
      ansible.builtin.apt:
        name:
          - i3
          - i3lock
          - i3status
          - compton
          - fonts-font-awesome
          - feh

    # polybar
    - name: Install polybar
      become: yes
      ansible.builtin.apt:
        name:
          - polybar
      register: polybar_result
      ignore_errors: true

    - name: Setup spotify status for polybar
      when: polybar_result is succeeded
      become: yes
      ansible.builtin.copy:
        src: ./polybar/spotify_status.py
        dest: ~/.config/polybar/spotify_status.py
        mode: u=rwx, g=r, o=r

    # Rofi
    - name: Install rofi
      become: yes
      tags:
        - rofi
      ansible.builtin.apt:
        name:
          - rofi
        state: present
      register: rofi_result
      ignore_errors: true

    - name: Copy rofi config file
      when: rofi_result is succeeded
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/config.rasi
        dest: ~/.config/rofi/config.rasi

    - name: Copy gruvbox common
      when: rofi_result is succeeded
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/gruvbox-common.rasinc
        dest: ~/.config/rofi/gruvbox-common.rasi

    - name: Copy rofi gruvbox material theme
      when: rofi_result is succeeded
      tags:
        - rofi
      ansible.builtin.copy:
        src: ./rofi/gruvbox-material_theme.rasi
        dest: ~/.config/rofi/gruvbox-material_theme.rasi

    when: ansible_distribution == "Ubuntu"
