
- name: i3 wm playbook
  hosts: localhost
  tasks:
    - name: Apt update and upgrade
      become: yes
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

    # i3
    - name: Install i3
      become: yes
      tags:
        - i3
      ansible.builtin.apt:
        name:
          - i3
          - i3lock
          - i3status
          - compton
          - fonts-font-awesome
          - feh

    - name: Copy i3 config files
      ansible.builtin.copy:
        src: ../i3/config
        dest: ~/.config/i3/config
        mode: u=rwx,g=r,o=r

    # polybar
    - name: Install polybar
      become: yes
      ansible.builtin.apt:
        name:
          - polybar
      register: polybar_result
      ignore_errors: true

    - name: Create a directory for polybar if it does not exist
      when: polybar_result is succeeded
      ansible.builtin.file:
        path: ~/.config/polybar
        state: directory

    - name: Copy polybar config file
      when: polybar_result is succeeded
      ansible.builtin.copy:
        src: ../polybar/config
        dest: ~/.config/polybar/config
        mode: u=rwx,g=r,o=r

    - name: Copy polybar launch script
      when: polybar_result is succeeded
      ansible.builtin.copy:
        src: ../polybar/launch.sh
        dest: ~/.config/polybar/launch.sh
        mode: u=rwx,g=r,o=r

    - name: Setup spotify status for polybar
      when: polybar_result is succeeded
      ansible.builtin.copy:
        src: ../polybar/spotify_status.py
        dest: ~/.config/polybar/spotify_status.py
        mode: u=rwx,g=r,o=r

    # Rofi
    - name: Install rofi
      become: yes
      tags:
        - rofi
      ansible.builtin.apt:
        name:
          - rofi
        state: present
      register: rofi_result
      ignore_errors: true

    - name: Create a directory for rofi if it does not exist
      when: polybar_result is succeeded
      ansible.builtin.file:
        path: ~/.config/rofi
        state: directory

    - name: Copy rofi config file
      when: rofi_result is succeeded
      tags:
        - rofi
      ansible.builtin.copy:
        src: ../rofi/config.rasi
        dest: ~/.config/rofi/config.rasi

    - name: Copy gruvbox common
      when: rofi_result is succeeded
      tags:
        - rofi
      ansible.builtin.copy:
        src: ../rofi/gruvbox-common.rasinc
        dest: ~/.config/rofi/gruvbox-common.rasi

    - name: Copy rofi gruvbox material theme
      when: rofi_result is succeeded
      tags:
        - rofi
      ansible.builtin.copy:
        src: ../rofi/gruvbox-material_theme.rasi
        dest: ~/.config/rofi/gruvbox-material_theme.rasi

    # Alacritty terminal emulator
    - name: Install Alacritty dependencies
      become: yes
      ansible.builtin.apt:
        name:
          - cmake
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - libxkbcommon-dev
          - python3

      - name: Create a directory for alacritty source code
        ansible.builtin.file:
          path: ~/source-codes/
          state: directory

      - name: Just get information about the repository whether or not it has already been cloned locally
        ansible.builtin.git:
          repo: 'https://github.com/alacritty/alacritty.git'
          dest: ~/source-codes/
          clone: yes
          update: yes

        - name: Check if cargo is installed
          shell: command -v cargo
          register: cargo_exists
          ignore_errors: yes

        - name: Install rust
          ansible.builtin.import_tasks: rust-playbook.yaml
          when: cargo_exists is failed

        # TODO Finish this
        - name: Build alacritty using cargo
          community.general.cargo:
            name: alacritty
