---
- name: Build rust source playbook
  hosts: localhost

  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"

  tasks:
    - name: Download Installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    # - name: Install rust/cargo
    #   ansible.builtin.command: /tmp/sh.rustup.rs -y
    #   tags:
    #     - rust
